### PR TITLE
Show error message if there is an exception is starting server

### PR DESCRIPTION
**Pull request by raheelkhan**
Addressing the Issue #79

### CODE REVIEW

**Comment by samuelwilliams** [comment]
This is a really neat solution, but is there a way we can test this functionality?

**Comment by raheelkhan** [comment]
Thanks,

I am kind of confused how to test it.

One way I could think of that we set a flag something called $serverRunning and set it to false in the promise rejected block. This way we can use a getter for this property and assert it with boolean.

Would like to know your recommendations

Thanks
Raheel

**Comment by tterranigma** [comment]
Reposting here from #79:

```
Almost, I think. There is an error message but the exit code is 0. Shouldn't it be at at least 1?
```

**Comment by raheelkhan** [comment]
throw $exception does not work as expected. It just ends without any error. I pushed with exit(1) in the otherwise block

**Comment by raheelkhan** [comment]
I agree, But so far what I understand is that we are not able to throw Exception to the client code from the async code part.

Right now the EchoLogger event subscriber is attatch to the server class which itself is implements EventSubscriberInterface and the throw keyword has no effect there.

We can either put the exit function in EchoLogger or maybe a new class that listen to ServerExceptionEvent only and calls the exit function.

Not sure what is happening to throw statement, looks like its being catch somewhere when called from within async context.

**Comment by ivanstan** [comment]
I'd create a dedicated listener for that. Maybe call it `ExceptionTerminatorListener` or something more creative.

**Comment by tterranigma** [comment]
That seems to work great!

**Comment by samuelwilliams** [comment]
I don't think we should use the `SERVER_EXCEPTION` event because this gets called in the `onMessage` method and would exit the server everytime there is a malformed packet or something. It would probably be best to make a new Event called `SERVER_START_FAIL` which the subscriber can listen for.

**Comment by samuelwilliams** [comment]
Merged! Can someone contribute documentation, please?

**Pull request merged**
