### PR TITLE
Support projects that use Symfony 5

### PR DESCRIPTION
**Pull request by ampaze**

### CODE REVIEW

**Comment by ampaze** [comment]
Is there something I can do to help move this along? 

cc: @samuelwilliams @xaoseric

**Comment by ampaze** [comment]
Is there still anyone maintaining this repository?

**Comment by xaoseric** [comment]
Hi @ampaze I will be working on an upgrade to Symfony 6.

**Comment by ampaze** [comment]
> Hi @ampaze I will be working on an upgrade to Symfony 6.

I doubt that anybody will merge it ... 😢

**Comment by xaoseric** [comment]
@ampaze that is why I have a fork of it.

**Pull request closed without merging**
