### PR TITLE
PhpDnsServer phar and cli phar

### PR DESCRIPTION
**Pull request by xaoseric**
Adds the beginning of a cli interface for PhpDnsServer, and a filesystem config for loading all .json files from a zones directory. 

Some additional ideas, if php is running on linux or unix we could default to /etc/phpdnsserver/settings.json  or /etc/phpdns.conf for a config file

### CODE REVIEW

**Comment by xaoseric** [comment]
latest push defaults to the current directory on windows an /etc/phpdnsserver on unix, will add support for specifying a custom directory in a phpdns.json file

**Comment by xaoseric** [comment]
The test files have been fixed.

**Comment by xaoseric** [comment]
added php based installer to create folders on unix systems, and the default config file. Also updated the readme to reflect the changes and additions.

**Comment by samuelwilliams** [comment]
Thanks for the PR!
As this is a large PR, it will take a bit of time to review.

At a first glance, I would say that there should be some tests associated with the PR. Also, since there is a coding standards config file associated with the project, you should run php-cs-fixer against the branch.

We will look into the code and give you some feedback.

Thank you again!

**Comment by xaoseric** [comment]
@samuelwilliams I have run php-cs-fixer against the branch as suggested. 

I made sure to keep the Server class backwards compatible as much as possible so that existing integrations will continue to work, by default unless true is passed to the constructor for using the new filesystem, it won't be used, unless it is run from the phpdnsserver.phar file which we have the ability to release now. For a 4.0 release, we could to change it up so that you can save records to .json for the filesystem backend.

**Comment by xaoseric** [comment]
@samuelwilliams any update on this?

**Pull request merged**
