### PR TITLE
Resolver interface changes only

### PR DESCRIPTION
**Pull request by ivanstan**
These are the changes @codenamegary probably cherry picked from my previous PR. I will create branches for future features as I go.

### CODE REVIEW

**Comment by ivanstan** [comment]
@codenamegary what should I do with the rest of changes? Open a new repository or would this be merged as well?

**Comment by codenamegary** [comment]
@ivanstan - This isn't my repository so I can't really say. I don't have write permissions here. Will need to wait for @yswery to chime in. Probably best just to maintain the rest of the changes in your fork until you hear from him.

**Comment by ivanstan** [comment]
I closed the previous "big one" MR and started new repository "the full application" php dns server in docker. https://github.com/ivanstan/php-dns, feel free to join

**Comment by yswery** [comment]
So Sorry for such a delay in looking at this PR, I totally didnt get a notification (fixed now) and hence just saw this by chance

Thank you for the cleaning up for the PSR2 code style and the interface

**Pull request merged**
