### PR TITLE
fixes phpunit tests and support for yaml configurations

### PR DESCRIPTION
**Pull request by ivanstan**
For my taste yaml files are more suitable to hold dns records, so I made this YamlResolver that extends JsonResolver

### CODE REVIEW

**Comment by samuelwilliams** [comment]
Not counting HHVM, but Travis build is currently failing...

**Comment by ivanstan** [comment]
Sorry for mess, it was phpunit version.

Changes in this commits are:
- updated phpunit to version ~6.5
- updated php-code-coverage to: ^5.3
- Updated tests to newer phpunit version, they now extend TestCase class
- Removed build for php 5.6 (I hope we all agree on that)
- Added YamlResolver with recods in yaml format
- Added test for YamlResolver

**Comment by samuelwilliams** [comment]
I think this is a great feature to add, but the YamlResolverTest doesn't make any assertions so no part of your new feature is tested.

With regard to updating the PHP version, I was waiting on @yswery to render his verdict on when to stop coding for PHP5

**Comment by ivanstan** [comment]
YamlResolverTest extends the JsonResolverTest, so it will use tests from that class, only difference how record array is loaded - in overriden setUp method. I plan to add some tests for invalid yaml formats in future.

**Comment by ivanstan** [comment]
Maybe it would be better to merge this to version-1 branch?

**Comment by samuelwilliams** [comment]
this has been merged into version-1

**Pull request closed without merging**
